### ISSUE TITLE
Avoiding need for postCSS and npm bits for hugo server

### ISSUE THREAD

**Issue by hartzell** [google/docsy-example#52]
I seem to need to have PostCSS set up in order to run hugo [server] on the demo site.

What would I need to do to include the post-processed bits in my copy of the site so that a simple `hugo server` would work?

Thanks!

**Comment by hartzell** [comment]
ping @LisaFC

**Comment by LisaFC** [comment]
So the post-processed bits don't really exist anywhere (they're not in the repo as they're generated on the fly every time the site is built), so you do need PostCSS to generate the site for the first time. Once you've done it once you can run hugo server as many times as you like, or even commit the generated files to a repo if you don't want to have to use PostCSS in your regular build.

If you're really stuck someone (me?) might be able to create a copy of the site repo and push the generated resources to it.

**Comment by hartzell** [comment]
I think that I'm asking a simpler question, namely:

- which generated bits do I need to commit to avoid running PostCSS every time (but still rebuild the rest of the site)?

The README makes it sound as if one only needs PostCSS if one changes the SCCS bits but it seems like it's *always* needed.

**Thanks!**

**Comment by LisaFC** [comment]
Ah gotcha! Ok, yes, you need PostCSS the first time you build the site (because otherwise it has eg no CSS files), and then after that you can commit/use the generated /resources/ folder and you should have everything you need (unless you change the SCSS and need to regenerate the files).

We used to do that as a workaround for CICD with Netlify before they upgraded their servers to support "extended" Hugo, and the Hugo docs site does it:
https://github.com/gohugoio/hugoDocs/tree/master/resources

**Comment by hartzell** [comment]
Looks like just removing `resources/` from the `.gitignore` will do what I'm looking for.

Thanks!
