### ISSUE TITLE
Commit messages in every page

### ISSUE THREAD

**Issue by MAlexGR** [google/docsy-example#96]
I noticed that at the end of each page of my site, a message like: `Last modified 19.12.2020: Δημιουργία ενότητας για την R (bdbe62b)` (I' m writing in greek), appears every time I edit the corresponding file and commit it to my GitHub repo.

Does anyone know what it is about and how can I hide / delete it? I noticed that this link, and any similar, directs me to the original repo of docsy example (something like `https://github.com/google/docsy-example/ commit/bdbe62ba650df186ba3e4f9db6bc67900216bd11`) but a 404 page shows up.

Any idea?

**Comment by LisaFC** [comment]
See my comment on #98 for checking where the docsy-example link bit is coming from (it uses the same github_repo param) - if it's working correctly it should have a link to your actual commit, which your users may find useful for seeing how up-to-date the page is, what the most recent update was, etc.

We don't have a param yet to hide the entire "Last modified" note, but if you want to just have the date rather than the entire message there's a workaround here: https://github.com/google/docsy/issues/246
